### ISSUE TITLE
I didnt create ip adress

### ISSUE THREAD

**Issue by Mecitinceoglu** [bigtreetech/BTT-SD-TF-Cloud-V1.0#19]
Hello to everyone ,
I'm trying to get ip address from Arduino IDE but it always says delay.

It doesn't give any ip. I have tried with different sd cards. But the problem is the same. Is there something I did wrong?
Thank you.

**Comment by Mecitinceoglu** [comment]
![image](https://user-images.githubusercontent.com/49680174/96353312-67c46480-10d3-11eb-957c-cafa52926c25.png)

**Comment by oldman4U** [comment]
Have you made the firmware update?

**Comment by Mecitinceoglu** [comment]
> Have you made the firmware update?

Hi again ,

Yes ı update to firimware.I take firmware from this page and upgrade with bin file.

**Comment by oldman4U** [comment]
So you have an SD card in the unit which has the SSID and Password of your network and there are no white spaces in your SSID? The SD card is <8GB and FAT32 and the textile withe the SSID/Password is plain text?

**Comment by Mecitinceoglu** [comment]
Yes I Have a 16 gb Sd card and there arent white space in my ssid an password SSID/Password is plain text.

Just I use 16GB SD card is it problem ?

**Comment by Mecitinceoglu** [comment]
I tried with 4 gb sd card i'm live in same problem

**Comment by oldman4U** [comment]
Your router has DHCP activated?

Maybe your router shows new device and the IP address?

When you start, what does the blued LED during the first 2 minutes?

**Comment by oldman4U** [comment]
Any news?

**Comment by Mecitinceoglu** [comment]
Hi ,

i still can't get ip.I have a router but btt cloud not use router.It must produce ip.

Blue LED is not lit at startup.It starts to flash after a while, but no ip appears on the serial port screen.

And only Delay is written on the screen

**Comment by oldman4U** [comment]
The btt must get the ip from the router.

How long does it flash and does it stop for at least one minute?


Mecitinceoglu <notifications@github.com> schrieb am Do. 22. Okt. 2020 um
11:19:

**Comment by Mecitinceoglu** [comment]
Thank you I solved the problem :)
I thought that will create ip adress BTT :)
I should write to my self ssid and password.
Thank you for support.

**Comment by oldman4U** [comment]
Perfect!

Please close the ticket.

Thank you

**Comment by Mecitinceoglu** [comment]
Thank you again.

**Comment by oldman4U** [comment]
👍🏻

Have fun

Mecitinceoglu <notifications@github.com> schrieb am Do. 22. Okt. 2020 um
20:52:
