### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by gerthalberg** [bigtreetech/BTT-SD-TF-Cloud-V1.0#22]
Would it be possible to extend the functionality of the module - such that it could also function as an ESP3D device together with having the TF card upload possibility.

**Comment by oldman4U** [comment]
I believe this has to be answered by @luc-github

**Comment by luc-github** [comment]
https://github.com/luc-github/ESP3D/issues/454

**Comment by oldman4U** [comment]
Thank you Luc. 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by luc-github** [comment]
@oldman4U  Are you asking to me to close ticket ?

**Comment by oldman4U** [comment]
No, but the owner of this ticket 😁

Luc <notifications@github.com> schrieb am Fr. 11. Dez. 2020 um 21:35:

**Comment by gerthalberg** [comment]
,-

**Comment by oldman4U** [comment]
Thank you
