### ISSUE TITLE
SD Cloud

### ISSUE THREAD

**Issue by pacocatech** [bigtreetech/BTT-SD-TF-Cloud-V1.0#35]
Hello,
When I'm trying to configure my SD Cloud by adding the SETUP.INI file I'm getting this error on the Serial Monitor:

![image](https://user-images.githubusercontent.com/70729684/133109459-3ff767ee-b551-4b9a-b1b5-01088011239b.png)

And I never get the connection IP.

**Comment by lierepieteres** [comment]
i have saved the ini file in small letters like this  setup.ini and not SETUP.INI after that its reading the file

**Comment by pacocatech** [comment]
@lierepieteres thanks a lot!!! solved my problem!
