### ISSUE TITLE
Connecting from MacOs and Linux

### ISSUE THREAD

**Issue by okashpurenko** [bigtreetech/BTT-SD-TF-Cloud-V1.0#7]
What protocol is used?
I'm trying 
smb://192.168.1.104/DavWWWRoot, cifs:// , nfs://,....

How to connect correctly?
Windows remote folder is works

**Comment by oldman4U** [comment]
Does this help?

https://github.com/bigtreetech/BTT-SD-TF-Cloud-V1.0/issues/4

**Comment by okashpurenko** [comment]
I was able to connect (MacOs)
http://192.168.1.104 -> without folder
the username and password must also be filled in, anything but empty
Looks weird but works

**Comment by destroyer-dcf** [comment]
I'm trying this with sonoma osx and it doesn't work....has anyone found it working....???
