### ISSUE TITLE
Impossible to connect

### ISSUE THREAD

**Issue by hantrax** [bigtreetech/BTT-SD-TF-Cloud-V1.0#9]
HI..I have received yesterday a BTT SD Cloud v1.0
I have followed your instruction and I have connected it to my wifi.
I have connected it to my BTT TFT 35 and I ran a print. after a few minutes the print stopped.
I have downloaded new firmware and flashed it to the BTT SD Cloud
Now I can't connect it to my wifi network.
any idea?

**Comment by NAPCAL** [comment]
Just found this out on my BTT Pro V1.1 using Marlin 2.0.6.
Configuration_adv.h 
When selecting #define SDCARD_CONNECTION ONBOARD (Configuration_adv.h), the TF cloud device will not start the Blue led blinking (when trying to connect to WIFI) and as a result, can not connect to the device via computer for file transfer.

By changing this selection to #define SDCARD_CONNECTION LCD (Configuration_adv.h) will allow the TF cloud to connect for usage.

**Comment by oldman4U** [comment]
Hi hantrax.

What is the status of the reported issue?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by hantrax** [comment]
After a firmware update I can use it..but the link is not stable...

**Comment by oldman4U** [comment]
Not stable in terms of...?
